fix(github-action):  fixing github action build
Co-authored-by: Abhishek Agarwal <abhishekagarwal@aagarwal-mbp1.local>

diff --git a/.github/workflows/pull_request.yml b/.github/workflows/pull_request.yml
--- a/.github/workflows/pull_request.yml
+++ b/.github/workflows/pull_request.yml
@@ -38,7 +38,7 @@ jobs:
       - name: Set up Go 1.16
         uses: actions/setup-go@v2
         with:
-          go-version: 1.16.5
+          go-version: 1.16.15
 
       - name: Format test
         run: make format
@@ -68,43 +68,49 @@ jobs:
       - name: Checkout
         uses: actions/checkout@v2
 
+      - name: Set up Go 1.16
+        uses: actions/setup-go@v2
+        with:
+          go-version: 1.16.15
+
       - name: Unit test
         run: make test
 
       - name: Upload Coverage Report
         uses: codecov/codecov-action@v1
 
-  bdd-test:
-    needs: ['unit-test']
-    runs-on: ubuntu-latest
-    strategy:
-      fail-fast: true
-      matrix:
-        kubernetes: [v1.22.1]
-    steps:
-      - name: Checkout
-        uses: actions/checkout@v2
-
-      - name: Set up Go 1.16
-        uses: actions/setup-go@v2
-        with:
-          go-version: 1.16.5
-
-      - name: Setup Minikube-Kubernetes
-        uses: manusa/actions-setup-minikube@v2.3.0
-        with:
-          minikube version: v1.16.0
-          kubernetes version: ${{ matrix.kubernetes }}
-          github token: ${{ secrets.GITHUB_TOKEN }}
-
-      - name: Build images locally
-        run: make lvm-driver-image || exit 1;
-
-      - name: bootstrap
-        run: make bootstrap
-
-      - name: Running tests
-        run: ./ci/ci-test.sh
+# TODO Add below bdd-test action once bdd tests are ready
+#  bdd-test:
+#    needs: ['unit-test']
+#    runs-on: ubuntu-latest
+#    strategy:
+#      fail-fast: true
+#      matrix:
+#        kubernetes: [v1.22.1]
+#    steps:
+#      - name: Checkout
+#        uses: actions/checkout@v2
+#
+#      - name: Set up Go 1.16
+#        uses: actions/setup-go@v2
+#        with:
+#          go-version: 1.16.5
+#
+#      - name: Setup Minikube-Kubernetes
+#        uses: manusa/actions-setup-minikube@v2.3.0
+#        with:
+#          minikube version: v1.16.0
+#          kubernetes version: ${{ matrix.kubernetes }}
+#          github token: ${{ secrets.GITHUB_TOKEN }}
+#
+#      - name: Build images locally
+#        run: make lvm-driver-image || exit 1;
+#
+#      - name: bootstrap
+#        run: make bootstrap
+#
+#      - name: Running tests
+#        run: ./ci/ci-test.sh
 
   data-populator:
     runs-on: ubuntu-latest
@@ -113,46 +119,6 @@ jobs:
       - name: Checkout
         uses: actions/checkout@v2
 
-      - name: Set Image Org
-        # sets the default IMAGE_ORG to openebs
-        run: |
-          [ -z "${{ secrets.IMAGE_ORG }}" ] && IMAGE_ORG=openebs || IMAGE_ORG=${{ secrets.IMAGE_ORG }}
-          echo "IMAGE_ORG=${IMAGE_ORG}" >> $GITHUB_ENV
-
-      - name: Set Build Date
-        id: date
-        run: |
-          echo "::set-output name=DATE::$(date -u +'%Y-%m-%dT%H:%M:%S%Z')"
-
-      - name: Set Tag
-        run: |
-          BRANCH="${GITHUB_REF##*/}"
-          CI_TAG=${BRANCH#v}-ci
-          if [ ${BRANCH} = "develop" ]; then
-            CI_TAG="ci"
-          fi
-          echo "TAG=${CI_TAG}" >> $GITHUB_ENV
-          echo "BRANCH=${BRANCH}" >> $GITHUB_ENV
-
-      - name: Docker meta
-        id: docker_meta
-        uses: crazy-max/ghaction-docker-meta@v1
-        with:
-          # add each registry to which the image needs to be pushed here
-          images: |
-            ${{ env.IMAGE_ORG }}/data-populator
-            quay.io/${{ env.IMAGE_ORG }}/data-populator
-            ghcr.io/${{ env.IMAGE_ORG }}/data-populator
-          tag-latest: false
-          tag-custom-only: true
-          tag-custom: |
-            ${{ env.TAG }}
-
-      - name: Print Tag info
-        run: |
-          echo "BRANCH: ${BRANCH}"
-          echo "${{ steps.docker_meta.outputs.tags }}"
-
       - name: Set up QEMU
         uses: docker/setup-qemu-action@v1
         with:
@@ -164,40 +130,15 @@ jobs:
         with:
           version: v0.5.1
 
-      - name: Login to Docker Hub
-        uses: docker/login-action@v1
-        with:
-          username: ${{ secrets.DOCKERHUB_USERNAME }}
-          password: ${{ secrets.DOCKERHUB_TOKEN }}
-
-      - name: Login to Quay
-        uses: docker/login-action@v1
-        with:
-          registry: quay.io
-          username: ${{ secrets.QUAY_USERNAME }}
-          password: ${{ secrets.QUAY_TOKEN }}
-
-      - name: Login to GHCR
-        uses: docker/login-action@v1
-        with:
-          registry: ghcr.io
-          username: ${{ github.actor }}
-          password: ${{ secrets.GITHUB_TOKEN }}
-
-      - name: Build & Push Image
+      - name: Build
         uses: docker/build-push-action@v2
         with:
           context: .
           file: ./buildscripts/populator/data/data-populator.Dockerfile
-          push: true
+          push: false
           platforms: linux/amd64, linux/arm64
           tags: |
-            ${{ steps.docker_meta.outputs.tags }}
-          build-args: |
-            DBUILD_DATE=${{ steps.date.outputs.DATE }}
-            DBUILD_REPO_URL=https://github.com/openebs/data-populator
-            DBUILD_SITE_URL=https://openebs.io
-            BRANCH=${{ env.BRANCH }}
+            openebs/data-populator:ci
 
   rsync-populator:
     runs-on: ubuntu-latest
@@ -206,46 +147,6 @@ jobs:
       - name: Checkout
         uses: actions/checkout@v2
 
-      - name: Set Image Org
-        # sets the default IMAGE_ORG to openebs
-        run: |
-          [ -z "${{ secrets.IMAGE_ORG }}" ] && IMAGE_ORG=openebs || IMAGE_ORG=${{ secrets.IMAGE_ORG }}
-          echo "IMAGE_ORG=${IMAGE_ORG}" >> $GITHUB_ENV
-
-      - name: Set Build Date
-        id: date
-        run: |
-          echo "::set-output name=DATE::$(date -u +'%Y-%m-%dT%H:%M:%S%Z')"
-
-      - name: Set Tag
-        run: |
-          BRANCH="${GITHUB_REF##*/}"
-          CI_TAG=${BRANCH#v}-ci
-          if [ ${BRANCH} = "develop" ]; then
-            CI_TAG="ci"
-          fi
-          echo "TAG=${CI_TAG}" >> $GITHUB_ENV
-          echo "BRANCH=${BRANCH}" >> $GITHUB_ENV
-
-      - name: Docker meta
-        id: docker_meta
-        uses: crazy-max/ghaction-docker-meta@v1
-        with:
-          # add each registry to which the image needs to be pushed here
-          images: |
-            ${{ env.IMAGE_ORG }}/rsync-populator
-            quay.io/${{ env.IMAGE_ORG }}/rsync-populator
-            ghcr.io/${{ env.IMAGE_ORG }}/rsync-populator
-          tag-latest: false
-          tag-custom-only: true
-          tag-custom: |
-            ${{ env.TAG }}
-
-      - name: Print Tag info
-        run: |
-          echo "BRANCH: ${BRANCH}"
-          echo "${{ steps.docker_meta.outputs.tags }}"
-
       - name: Set up QEMU
         uses: docker/setup-qemu-action@v1
         with:
@@ -257,40 +158,15 @@ jobs:
         with:
           version: v0.5.1
 
-      - name: Login to Docker Hub
-        uses: docker/login-action@v1
-        with:
-          username: ${{ secrets.DOCKERHUB_USERNAME }}
-          password: ${{ secrets.DOCKERHUB_TOKEN }}
-
-      - name: Login to Quay
-        uses: docker/login-action@v1
-        with:
-          registry: quay.io
-          username: ${{ secrets.QUAY_USERNAME }}
-          password: ${{ secrets.QUAY_TOKEN }}
-
-      - name: Login to GHCR
-        uses: docker/login-action@v1
-        with:
-          registry: ghcr.io
-          username: ${{ github.actor }}
-          password: ${{ secrets.GITHUB_TOKEN }}
-
-      - name: Build & Push Image
+      - name: Build
         uses: docker/build-push-action@v2
         with:
           context: .
           file: ./buildscripts/populator/rsync/rsync-populator.Dockerfile
-          push: true
+          push: false
           platforms: linux/amd64, linux/arm64
           tags: |
-            ${{ steps.docker_meta.outputs.tags }}
-          build-args: |
-            DBUILD_DATE=${{ steps.date.outputs.DATE }}
-            DBUILD_REPO_URL=https://github.com/openebs/data-populator
-            DBUILD_SITE_URL=https://openebs.io
-            BRANCH=${{ env.BRANCH }}
+            openebs/rsync-populator:ci
 
   rsync-daemon:
     runs-on: ubuntu-latest
@@ -299,46 +175,6 @@ jobs:
       - name: Checkout
         uses: actions/checkout@v2
 
-      - name: Set Image Org
-        # sets the default IMAGE_ORG to openebs
-        run: |
-          [ -z "${{ secrets.IMAGE_ORG }}" ] && IMAGE_ORG=openebs || IMAGE_ORG=${{ secrets.IMAGE_ORG }}
-          echo "IMAGE_ORG=${IMAGE_ORG}" >> $GITHUB_ENV
-
-      - name: Set Build Date
-        id: date
-        run: |
-          echo "::set-output name=DATE::$(date -u +'%Y-%m-%dT%H:%M:%S%Z')"
-
-      - name: Set Tag
-        run: |
-          BRANCH="${GITHUB_REF##*/}"
-          CI_TAG=${BRANCH#v}-ci
-          if [ ${BRANCH} = "develop" ]; then
-            CI_TAG="ci"
-          fi
-          echo "TAG=${CI_TAG}" >> $GITHUB_ENV
-          echo "BRANCH=${BRANCH}" >> $GITHUB_ENV
-
-      - name: Docker meta
-        id: docker_meta
-        uses: crazy-max/ghaction-docker-meta@v1
-        with:
-          # add each registry to which the image needs to be pushed here
-          images: |
-            ${{ env.IMAGE_ORG }}/rsync-daemon
-            quay.io/${{ env.IMAGE_ORG }}/rsync-daemon
-            ghcr.io/${{ env.IMAGE_ORG }}/rsync-daemon
-          tag-latest: false
-          tag-custom-only: true
-          tag-custom: |
-            ${{ env.TAG }}
-
-      - name: Print Tag info
-        run: |
-          echo "BRANCH: ${BRANCH}"
-          echo "${{ steps.docker_meta.outputs.tags }}"
-
       - name: Set up QEMU
         uses: docker/setup-qemu-action@v1
         with:
@@ -350,40 +186,15 @@ jobs:
         with:
           version: v0.5.1
 
-      - name: Login to Docker Hub
-        uses: docker/login-action@v1
-        with:
-          username: ${{ secrets.DOCKERHUB_USERNAME }}
-          password: ${{ secrets.DOCKERHUB_TOKEN }}
-
-      - name: Login to Quay
-        uses: docker/login-action@v1
-        with:
-          registry: quay.io
-          username: ${{ secrets.QUAY_USERNAME }}
-          password: ${{ secrets.QUAY_TOKEN }}
-
-      - name: Login to GHCR
-        uses: docker/login-action@v1
-        with:
-          registry: ghcr.io
-          username: ${{ github.actor }}
-          password: ${{ secrets.GITHUB_TOKEN }}
-
-      - name: Build & Push Image
+      - name: Build
         uses: docker/build-push-action@v2
         with:
           context: .
           file: ./buildscripts/rsync/daemon/Dockerfile
-          push: true
+          push: false
           platforms: linux/amd64, linux/arm64
           tags: |
-            ${{ steps.docker_meta.outputs.tags }}
-          build-args: |
-            DBUILD_DATE=${{ steps.date.outputs.DATE }}
-            DBUILD_REPO_URL=https://github.com/openebs/data-populator
-            DBUILD_SITE_URL=https://openebs.io
-            BRANCH=${{ env.BRANCH }}
+            openebs/rsync-daemon:ci
 
   rsync-client:
     runs-on: ubuntu-latest
@@ -392,46 +203,6 @@ jobs:
       - name: Checkout
         uses: actions/checkout@v2
 
-      - name: Set Image Org
-        # sets the default IMAGE_ORG to openebs
-        run: |
-          [ -z "${{ secrets.IMAGE_ORG }}" ] && IMAGE_ORG=openebs || IMAGE_ORG=${{ secrets.IMAGE_ORG }}
-          echo "IMAGE_ORG=${IMAGE_ORG}" >> $GITHUB_ENV
-
-      - name: Set Build Date
-        id: date
-        run: |
-          echo "::set-output name=DATE::$(date -u +'%Y-%m-%dT%H:%M:%S%Z')"
-
-      - name: Set Tag
-        run: |
-          BRANCH="${GITHUB_REF##*/}"
-          CI_TAG=${BRANCH#v}-ci
-          if [ ${BRANCH} = "develop" ]; then
-            CI_TAG="ci"
-          fi
-          echo "TAG=${CI_TAG}" >> $GITHUB_ENV
-          echo "BRANCH=${BRANCH}" >> $GITHUB_ENV
-
-      - name: Docker meta
-        id: docker_meta
-        uses: crazy-max/ghaction-docker-meta@v1
-        with:
-          # add each registry to which the image needs to be pushed here
-          images: |
-            ${{ env.IMAGE_ORG }}/rsync-client
-            quay.io/${{ env.IMAGE_ORG }}/rsync-client
-            ghcr.io/${{ env.IMAGE_ORG }}/rsync-client
-          tag-latest: false
-          tag-custom-only: true
-          tag-custom: |
-            ${{ env.TAG }}
-
-      - name: Print Tag info
-        run: |
-          echo "BRANCH: ${BRANCH}"
-          echo "${{ steps.docker_meta.outputs.tags }}"
-
       - name: Set up QEMU
         uses: docker/setup-qemu-action@v1
         with:
@@ -443,37 +214,12 @@ jobs:
         with:
           version: v0.5.1
 
-      - name: Login to Docker Hub
-        uses: docker/login-action@v1
-        with:
-          username: ${{ secrets.DOCKERHUB_USERNAME }}
-          password: ${{ secrets.DOCKERHUB_TOKEN }}
-
-      - name: Login to Quay
-        uses: docker/login-action@v1
-        with:
-          registry: quay.io
-          username: ${{ secrets.QUAY_USERNAME }}
-          password: ${{ secrets.QUAY_TOKEN }}
-
-      - name: Login to GHCR
-        uses: docker/login-action@v1
-        with:
-          registry: ghcr.io
-          username: ${{ github.actor }}
-          password: ${{ secrets.GITHUB_TOKEN }}
-
-      - name: Build & Push Image
+      - name: Build
         uses: docker/build-push-action@v2
         with:
           context: .
           file: ./buildscripts/rsync/client/Dockerfile
-          push: true
+          push: false
           platforms: linux/amd64, linux/arm64
           tags: |
-            ${{ steps.docker_meta.outputs.tags }}
-          build-args: |
-            DBUILD_DATE=${{ steps.date.outputs.DATE }}
-            DBUILD_REPO_URL=https://github.com/openebs/data-populator
-            DBUILD_SITE_URL=https://openebs.io
-            BRANCH=${{ env.BRANCH }}
+            openebs/rsync-client:ci
